//! Integration test: drive `CodexSurface::install` over a tempdir and
//! prove the AGENTS.md managed-block contract holds end-to-end.

use std::fs;
use std::path::PathBuf;

use klasp_agents_codex::{CodexSurface, MANAGED_END, MANAGED_START};
use klasp_core::{AgentSurface, InstallContext};

const FIXTURE: &str = include_str!("fixtures/agents_md_with_other_tool.md");

fn ctx(repo_root: PathBuf) -> InstallContext {
    InstallContext {
        repo_root,
        dry_run: false,
        force: false,
        schema_version: 1,
    }
}

fn read(path: &std::path::Path) -> String {
    fs::read_to_string(path).expect("read AGENTS.md")
}

#[test]
fn install_creates_agents_md_when_missing() {
    let dir = tempfile::tempdir().unwrap();
    let surface = CodexSurface;

    let report = surface.install(&ctx(dir.path().to_path_buf())).unwrap();

    assert_eq!(report.agent_id, CodexSurface::AGENT_ID);
    assert!(!report.already_installed);
    assert_eq!(report.paths_written.len(), 1);

    let agents_md = dir.path().join("AGENTS.md");
    assert!(agents_md.is_file());
    let body = read(&agents_md);
    assert!(body.contains(MANAGED_START));
    assert!(body.contains(MANAGED_END));
}

#[test]
fn install_into_empty_file_emits_just_the_block() {
    let dir = tempfile::tempdir().unwrap();
    let agents_md = dir.path().join("AGENTS.md");
    fs::write(&agents_md, "").unwrap();

    let surface = CodexSurface;
    surface.install(&ctx(dir.path().to_path_buf())).unwrap();

    let body = read(&agents_md);
    assert!(body.starts_with(MANAGED_START));
}

#[test]
fn install_appends_to_existing_file_preserving_other_tool_content() {
    let dir = tempfile::tempdir().unwrap();
    let agents_md = dir.path().join("AGENTS.md");
    fs::write(&agents_md, FIXTURE).unwrap();

    let surface = CodexSurface;
    surface.install(&ctx(dir.path().to_path_buf())).unwrap();

    let body = read(&agents_md);

    // Foreign tool content untouched.
    assert!(body.contains("<!-- generated by some-other-tool: do not edit -->"));
    assert!(body.contains("Some other tool's section"));
    assert!(body.contains("<!-- end some-other-tool -->"));
    // User prose above and below survives.
    assert!(body.contains("Top-of-file prose another contributor wrote"));
    assert!(body.contains("Closing prose at the bottom of the file"));
    // klasp block now appended at the end.
    assert!(body.contains(MANAGED_START));
    assert!(body.contains(MANAGED_END));
}

#[test]
fn install_is_idempotent_running_twice_produces_no_diff() {
    let dir = tempfile::tempdir().unwrap();
    let agents_md = dir.path().join("AGENTS.md");
    fs::write(&agents_md, FIXTURE).unwrap();

    let surface = CodexSurface;

    surface.install(&ctx(dir.path().to_path_buf())).unwrap();
    let after_first = read(&agents_md);

    let report2 = surface.install(&ctx(dir.path().to_path_buf())).unwrap();
    let after_second = read(&agents_md);

    assert_eq!(
        after_first, after_second,
        "running install twice changed bytes"
    );
    assert!(report2.already_installed);
    assert!(report2.paths_written.is_empty());
}

#[test]
fn round_trip_install_then_uninstall_restores_original() {
    let dir = tempfile::tempdir().unwrap();
    let agents_md = dir.path().join("AGENTS.md");
    fs::write(&agents_md, FIXTURE).unwrap();

    let surface = CodexSurface;
    surface.install(&ctx(dir.path().to_path_buf())).unwrap();
    let paths = surface.uninstall(dir.path(), false).unwrap();

    assert_eq!(paths.len(), 1);
    let restored = read(&agents_md);
    assert_eq!(restored, FIXTURE, "round-trip mutated the file");
}

#[test]
fn round_trip_when_file_did_not_exist_removes_it() {
    let dir = tempfile::tempdir().unwrap();
    let agents_md = dir.path().join("AGENTS.md");
    assert!(!agents_md.exists());

    let surface = CodexSurface;
    surface.install(&ctx(dir.path().to_path_buf())).unwrap();
    assert!(agents_md.exists());

    surface.uninstall(dir.path(), false).unwrap();
    assert!(
        !agents_md.exists(),
        "uninstall did not remove a klasp-only AGENTS.md"
    );
}

#[test]
fn dry_run_writes_nothing_but_returns_preview() {
    let dir = tempfile::tempdir().unwrap();
    let agents_md = dir.path().join("AGENTS.md");
    fs::write(&agents_md, FIXTURE).unwrap();

    let surface = CodexSurface;
    let mut c = ctx(dir.path().to_path_buf());
    c.dry_run = true;
    let report = surface.install(&c).unwrap();

    // Disk untouched.
    assert_eq!(read(&agents_md), FIXTURE);
    // Preview populated.
    assert!(report.preview.is_some());
    assert!(report.paths_written.is_empty());
}

#[test]
fn detect_returns_true_when_agents_md_exists() {
    let dir = tempfile::tempdir().unwrap();
    let surface = CodexSurface;
    assert!(!surface.detect(dir.path()));

    fs::write(dir.path().join("AGENTS.md"), "").unwrap();
    assert!(surface.detect(dir.path()));
}

#[test]
fn hook_path_points_at_pre_commit() {
    let dir = tempfile::tempdir().unwrap();
    let surface = CodexSurface;
    let p = surface.hook_path(dir.path());
    assert!(p.ends_with(std::path::Path::new(".git/hooks/pre-commit")));
}

#[test]
fn settings_path_is_repo_root_agents_md() {
    let dir = tempfile::tempdir().unwrap();
    let surface = CodexSurface;
    assert_eq!(
        surface.settings_path(dir.path()),
        dir.path().join("AGENTS.md")
    );
}

#[test]
fn render_hook_script_is_empty_in_w1() {
    // W2 (#28) will fill this in. For W1, an empty render makes the
    // "no hook script written yet" contract structurally obvious.
    let surface = CodexSurface;
    let dir = tempfile::tempdir().unwrap();
    assert_eq!(
        surface.render_hook_script(&ctx(dir.path().to_path_buf())),
        ""
    );
}
