//! Converts an [`AdoptionPlan`] into a `klasp.toml` and writes it atomically.
//!
//! The generated TOML is built by hand (rather than via `toml::to_string`)
//! so that we can preserve comments and control the exact section ordering.
//! After writing, the generated TOML is validated by round-tripping it through
//! `klasp_core::ConfigV1::parse` — any generator bug is caught before the
//! file reaches the user's repo.
//!
//! See klasp-dev/klasp#97.

use std::io;
use std::path::{Path, PathBuf};

use crate::adopt::plan::{AdoptionPlan, ProposedCheckSource};

/// Write (or overwrite) `<repo_root>/klasp.toml` from the adoption plan.
///
/// Returns the absolute path of the written file on success.
///
/// # Errors
///
/// - `AlreadyExists` — `klasp.toml` already exists and `force` is `false`.
/// - `InvalidData`  — the generated TOML fails `ConfigV1::parse` (generator bug).
/// - Other `io::Error` variants propagated from filesystem operations.
pub fn write_klasp_toml(repo_root: &Path, plan: &AdoptionPlan, force: bool) -> io::Result<PathBuf> {
    let target = repo_root.join("klasp.toml");

    if target.exists() && !force {
        return Err(io::Error::new(
            io::ErrorKind::AlreadyExists,
            "klasp.toml already exists; pass --force to overwrite",
        ));
    }

    let toml_content = generate_toml(plan);

    // Safety-net: validate the generated TOML before touching the filesystem.
    klasp_core::ConfigV1::parse(&toml_content).map_err(|e| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("generated klasp.toml failed validation (generator bug): {e}"),
        )
    })?;

    crate::fs_util::atomic_write_text(&target, &toml_content)?;
    Ok(target)
}

/// Generate the TOML content for the given plan.
fn generate_toml(plan: &AdoptionPlan) -> String {
    let adopted_note = if plan.findings.is_empty() {
        "# adopted: no existing gates detected\n"
    } else {
        "# adopted: mirroring existing gates detected by `klasp init --adopt`\n"
    };

    let mut out = format!(
        "# klasp.toml — generated by `klasp init --adopt`\n\
         # Docs: https://github.com/klasp-dev/klasp\n\
         # Verify this install: run `klasp doctor`\n\
         {adopted_note}\
         \n\
         version = 1\n\
         \n\
         [gate]\n\
         agents = [\"claude_code\", \"codex\", \"aider\"]\n\
         policy = \"any_fail\"\n"
    );

    for finding in &plan.findings {
        for check in &finding.proposed_checks {
            out.push('\n');
            out.push_str("[[checks]]\n");
            out.push_str(&format!("name = \"{}\"\n", escape_toml_string(&check.name)));

            let trigger_items: Vec<String> = check
                .triggers
                .iter()
                .map(|t| format!("\"{}\"", escape_toml_string(t.as_str())))
                .collect();
            out.push_str(&format!(
                "triggers = [{{ on = [{}] }}]\n",
                trigger_items.join(", ")
            ));

            out.push_str(&format!("timeout_secs = {}\n", check.timeout_secs));

            out.push_str("[checks.source]\n");
            match &check.source {
                ProposedCheckSource::PreCommit {
                    hook_stage,
                    config_path,
                } => {
                    out.push_str("type = \"pre_commit\"\n");
                    if let Some(stage) = hook_stage {
                        out.push_str(&format!("hook_stage = \"{}\"\n", escape_toml_string(stage)));
                    }
                    if let Some(path) = config_path {
                        out.push_str(&format!(
                            "config_path = \"{}\"\n",
                            escape_toml_string(&path.display().to_string())
                        ));
                    }
                }
                ProposedCheckSource::Shell { command } => {
                    out.push_str("type = \"shell\"\n");
                    out.push_str(&format!("command = \"{}\"\n", escape_toml_string(command)));
                }
            }
        }
    }

    out
}

/// Minimal TOML string escaping: backslash and double-quote characters only.
/// TOML basic strings require `"` → `\"` and `\` → `\\`.
fn escape_toml_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;
    use crate::adopt::plan::{
        AdoptionPlan, ChainSupport, DetectedGate, GateType, ProposedCheck, ProposedCheckSource,
        TriggerKind,
    };

    fn pre_commit_plan() -> AdoptionPlan {
        AdoptionPlan {
            findings: vec![DetectedGate {
                gate_type: GateType::PreCommitFramework,
                source_path: PathBuf::from(".pre-commit-config.yaml"),
                proposed_checks: vec![ProposedCheck {
                    name: "pre-commit".to_string(),
                    triggers: vec![TriggerKind::Commit],
                    timeout_secs: 120,
                    source: ProposedCheckSource::PreCommit {
                        hook_stage: None,
                        config_path: None,
                    },
                }],
                chain_support: ChainSupport::ManualOnly,
                manual_chain_instructions: None,
                warnings: vec![],
            }],
        }
    }

    fn shell_plan(command: &str) -> AdoptionPlan {
        AdoptionPlan {
            findings: vec![DetectedGate {
                gate_type: GateType::LintStaged,
                source_path: PathBuf::from("package.json"),
                proposed_checks: vec![ProposedCheck {
                    name: "lint-staged".to_string(),
                    triggers: vec![TriggerKind::Commit],
                    timeout_secs: 120,
                    source: ProposedCheckSource::Shell {
                        command: command.to_string(),
                    },
                }],
                chain_support: ChainSupport::ManualOnly,
                manual_chain_instructions: None,
                warnings: vec![],
            }],
        }
    }

    #[test]
    fn writes_and_parses_pre_commit_check() {
        let tmp = tempfile::TempDir::new().unwrap();
        let plan = pre_commit_plan();
        let written = write_klasp_toml(tmp.path(), &plan, false).unwrap();
        assert_eq!(written, tmp.path().join("klasp.toml"));

        let content = std::fs::read_to_string(&written).unwrap();
        let config =
            klasp_core::ConfigV1::parse(&content).expect("generated TOML should parse cleanly");
        assert_eq!(config.checks.len(), 1);
        assert_eq!(config.checks[0].name, "pre-commit");
        assert!(matches!(
            &config.checks[0].source,
            klasp_core::CheckSourceConfig::PreCommit { hook_stage, config_path }
                if hook_stage.is_none() && config_path.is_none()
        ));
    }

    #[test]
    fn writes_and_parses_shell_check() {
        let tmp = tempfile::TempDir::new().unwrap();
        let plan = shell_plan("pnpm exec lint-staged");
        let written = write_klasp_toml(tmp.path(), &plan, false).unwrap();
        let content = std::fs::read_to_string(&written).unwrap();
        let config = klasp_core::ConfigV1::parse(&content).unwrap();
        assert_eq!(config.checks.len(), 1);
        assert!(matches!(
            &config.checks[0].source,
            klasp_core::CheckSourceConfig::Shell { command }
                if command == "pnpm exec lint-staged"
        ));
    }

    #[test]
    fn errors_if_file_exists_without_force() {
        let tmp = tempfile::TempDir::new().unwrap();
        let plan = pre_commit_plan();
        write_klasp_toml(tmp.path(), &plan, false).unwrap();
        let err = write_klasp_toml(tmp.path(), &plan, false).unwrap_err();
        assert_eq!(err.kind(), io::ErrorKind::AlreadyExists);
    }

    #[test]
    fn overwrites_with_force() {
        let tmp = tempfile::TempDir::new().unwrap();
        let plan = pre_commit_plan();
        write_klasp_toml(tmp.path(), &plan, false).unwrap();
        let result = write_klasp_toml(tmp.path(), &plan, true);
        assert!(result.is_ok(), "force should allow overwrite");
    }

    #[test]
    fn empty_plan_writes_minimal_scaffold() {
        let tmp = tempfile::TempDir::new().unwrap();
        let plan = AdoptionPlan::default();
        let written = write_klasp_toml(tmp.path(), &plan, false).unwrap();
        let content = std::fs::read_to_string(&written).unwrap();
        let config = klasp_core::ConfigV1::parse(&content).unwrap();
        assert!(config.checks.is_empty());
        assert!(content.contains("no existing gates detected"));
    }

    #[test]
    fn pre_commit_with_hook_stage_and_config_path() {
        let tmp = tempfile::TempDir::new().unwrap();
        let plan = AdoptionPlan {
            findings: vec![DetectedGate {
                gate_type: GateType::PreCommitFramework,
                source_path: PathBuf::from(".pre-commit-config.yaml"),
                proposed_checks: vec![ProposedCheck {
                    name: "pre-commit-push".to_string(),
                    triggers: vec![TriggerKind::Push],
                    timeout_secs: 120,
                    source: ProposedCheckSource::PreCommit {
                        hook_stage: Some("pre-push".to_string()),
                        config_path: Some(PathBuf::from("tools/pre-commit.yaml")),
                    },
                }],
                chain_support: ChainSupport::ManualOnly,
                manual_chain_instructions: None,
                warnings: vec![],
            }],
        };
        let written = write_klasp_toml(tmp.path(), &plan, false).unwrap();
        let content = std::fs::read_to_string(&written).unwrap();
        let config = klasp_core::ConfigV1::parse(&content).unwrap();
        assert_eq!(config.checks.len(), 1);
        match &config.checks[0].source {
            klasp_core::CheckSourceConfig::PreCommit {
                hook_stage,
                config_path,
            } => {
                assert_eq!(hook_stage.as_deref(), Some("pre-push"));
                assert_eq!(
                    config_path.as_ref().map(|p| p.display().to_string()),
                    Some("tools/pre-commit.yaml".to_string())
                );
            }
            other => panic!("expected PreCommit, got {other:?}"),
        }
    }

    #[test]
    fn toml_string_escaping_works() {
        assert_eq!(escape_toml_string(r#"foo"bar"#), r#"foo\"bar"#);
        assert_eq!(escape_toml_string(r"foo\bar"), r"foo\\bar");
        assert_eq!(escape_toml_string("simple"), "simple");
    }

    #[test]
    fn header_does_not_mention_mode_mirror() {
        let tmp = tempfile::TempDir::new().unwrap();
        let plan = AdoptionPlan::default();
        let written = write_klasp_toml(tmp.path(), &plan, false).unwrap();
        let content = std::fs::read_to_string(&written).unwrap();
        assert!(
            !content.contains("--mode mirror"),
            "header should not hardcode --mode mirror"
        );
    }
}
